config/routes.rb
Rails.application.routes.draw do
  
  devise_for :authors
  
  resources :posts do
    resources :comments
  end
  
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :body
  has_many :comments

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :set_draftsman_whodunnit
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_author!, only: %i[new create edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    set_post
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevThoughts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=PT+Serif:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-light container">
        <div class="logo">
          <a href="index.html">NC</a>
        </div>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <div class="navbar-nav ml-auto">
            <a href="https://cathella.github.io/" class="nav-item nav-link mr-4">Home</a>
            <a href="https://cathella.github.io/projects.html" class="nav-item nav-link mr-4">Projects</a>
            <a href="/" class="nav-item nav-link mr-4">Blog</a>
            <a href="https://cathella.github.io/templates.html" class="nav-item nav-link mr-4">Templates</a>
            <% if author_signed_in? %>
              <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: 'nav-item nav-link' %>
            <% end %>
          </div>
        </div>
      </nav>
    </header>

    <div class="container my-5 pt-5">
    <%= yield %>
    </div>

    <footer class="container pt-5 mb-5 border-top">
      <nav class="d-flex align-items-center justify-content-center flex-wrap">
        <div class="d-flex">
          <a class="mr-4" href="https://github.com/Cathella"><i class="fab fa-github fa-lg text-muted"></i></a>
          <a class="mr-4" href="https://twitter.com/cathella9"><i class="fab fa-twitter fa-lg text-muted"></i></a>
          <a href="https://www.linkedin.com/in/nakitto-catherine2020/"><i class="fab fa-linkedin-in fa-lg text-muted"></i></a>
        </div>
      </nav>
    </footer>

    <script
		src="https://kit.fontawesome.com/7290f27402.js"
		crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-3 mb-5">
    <%= form.label :title, 'Post Heading', class: 'label text-purple mb-3', style: 'font-family: "PT Serif", serif; font-size: 20px;' %>
    <%= form.text_field :title, placeholder: 'Enter title', class: 'form-control rounded-0 text-muted input', style: 'font-family: "PT Serif", serif;' %>
  </div>

  <div class="field mt-3">
    <%= form.label :body, 'Tell your story', class: 'label text-purple mb-3', style: 'font-family: "PT Serif", serif; font-size: 20px;' %>
    <%= form.rich_text_area :body, placeholder: 'Once upon a time...', class: 'form-control rounded-0 text-muted', style: 'font-size: 18px; border: none; border-left: 1px dashed #cf6fd8;' %>
  </div>

  <div class="actions mt-3">
    <%= form.submit 'Submit Post', class: 'btn btn-purple rounded-0 px-5 py-3 shadow mt-4' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-lg-9 mx-auto mb-5">
      <h2 class="mb-5 pb-4">My Dev-thoughts</h2>

      <% @posts.each do |post| %>
        <h3><%= link_to post.title, post, class: 'link-color', style: 'text-decoration: underline' %></h3>
        <div class="text-muted my-3">
          <%= post.body.to_plain_text.truncate_words(65) %>
        </div>
        <div class="mb-5">
          <%= link_to 'Read more', post, class: 'mr-4 text-purple' %>
          <% if author_signed_in? %>
            <%= link_to 'Edit Post', edit_post_path(post), class: 'mr-4 text-purple' %>
            <%= link_to 'Delete Post', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-purple' %>
          <% end %>
        </div>
      <% end %>

      <% if author_signed_in? %>
        <div class="">
          <%= link_to 'Create a New Post', new_post_path, class: 'btn btn-purple rounded-0 px-5 py-3 shadow' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="">
<%= link_to '<i class="fas fa-arrow-left mr-2"></i>Back to Posts'.html_safe, posts_path, class: 'text-purple' %>
</div>

<h2 class="text-center mb-5">New Post</h2>

<div class="row">
  <div class="col-lg-8 mx-auto mb-5">
    <%= render 'form', post: @post %>
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row mb-5">
  <div class="col-lg-9 mx-auto">
    <div class="">
    <%= link_to '<i class="fas fa-arrow-left mr-2"></i>Back to Posts'.html_safe, posts_path, class: 'text-purple' %>
    </div>

    <h2 class="border-bottom pb-3 mb-4 mt-3">
      <%= @post.title %>
    </h2>

    <div class="mb-4 text-muted">
      <%= @post.body %>
    </div>

    <div>
      <% if author_signed_in? %>
        <%= link_to 'Edit Post', edit_post_path(@post), class: 'mr-4 text-purple' %>
      <% end %>
    </div>

    <!--
    <div class="mt-4">
      <%= form_for([@post, @post.comments.build]) do |form| %>
        <div class="field mb-3">
          <%= form.text_field :name, class: 'form-control', placeholder: 'Your name', style: 'height: 2.9em'%>
        </div>
        <div class="field mb-4">
          <%= form.text_area :body, class: 'form-control', placeholder: 'Your comment', style: 'height: 5.5em'%>
        </div>
        <div class="actions">
          <%= form.submit 'Add comment', class: 'btn btn-purple py-3 px-5 rounded-0' %>
        </div>
      <% end %>
    </div>

    <div class="mt-5">
      <% @comments.each do |comment| %>
          <div class="font-weight-bold" style="font-size: 1.2em"><%= comment.name %></div>
          <small class="text-muted">Posted on <%= comment.created_at %></small>
          <p class="border-bottom mt-2 pb-2 text-muted"><%= comment.body %></p>
          <% if author_signed_in? %>
            <%= link_to 'Delete comment', [comment.post, comment], method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>
          <% end %>
      <% end %>
    </div>
    -->
  </div>
</div>